In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("netflix_data.csv")

In [3]:
data

,show_id,type,title,director,cast,country,date_added,release_year,duration,description,genre
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",2020,4,In a future where the elite inhabit an island ...,International TV
1,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",2016,93,After a devastating earthquake hits Mexico Cit...,Dramas
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,78,"When an army recruit is found dead, his fellow...",Horror Movies
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",2009,80,"In a postapocalyptic world, rag-doll robots hi...",Action
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",2008,123,A brilliant group of students become card-coun...,Dramas
...,...,...,...,...,...,...,...,...,...,...,...
7782,s7783,Movie,Zozo,Josef Fares,"Imad Creidi, Antoinette Turk, Elias Gergi, Car...",Sweden,"October 19, 2020",2005,99,When Lebanon's Civil War deprives Zozo of his ...,Dramas
7783,s7784,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,111,A scrappy but poor boy worms his way into a ty...,Dramas
7784,s7785,Movie,Zulu Man in Japan,NaN,Nasty C,NaN,"September 25, 2020",2019,44,"In this documentary, South African rapper Nast...",Documentaries
7785,s7786,TV Show,Zumbo's Just Desserts,NaN,"Adriano Zumbo, Rachel Khoo",Australia,"October 31, 2020",2019,1,Dessert wizard Adriano Zumbo looks for the nex...,International TV
7786,s7787,Movie,ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS,Sam Dunn,NaN,United Kingdom,"March 1, 2020",2019,90,This documentary delves into the mystique behi...,Documentaries

In [4]:
data.count()

show_id         7787
type            7787
title           7787
director        5398
cast            7069
country         7280
date_added      7777
release_year    7787
duration        7787
description     7787
genre           7787
dtype: int64

In [5]:
data["cast"] = data["cast"].replace(np.nan, "None")

In [6]:
data.count()

show_id         7787
type            7787
title           7787
director        5398
cast            7787
country         7280
date_added      7777
release_year    7787
duration        7787
description     7787
genre           7787
dtype: int64

Adding column num_of_cast

In [9]:
def castColumn(cast):
    i=0
    for i in range(0,7788):
        a = data.loc[i, "cast"]
        number = len(a.split(','))
        return number
        i=i+1

In [10]:
data["num_of_cast"] = data["cast"].apply(castColumn)

In [11]:
data

,show_id,type,title,director,cast,country,date_added,release_year,duration,description,genre,num_of_cast
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",2020,4,In a future where the elite inhabit an island ...,International TV,11
1,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",2016,93,After a devastating earthquake hits Mexico Cit...,Dramas,11
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,78,"When an army recruit is found dead, his fellow...",Horror Movies,11
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",2009,80,"In a postapocalyptic world, rag-doll robots hi...",Action,11
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",2008,123,A brilliant group of students become card-coun...,Dramas,11
...,...,...,...,...,...,...,...,...,...,...,...,...
7782,s7783,Movie,Zozo,Josef Fares,"Imad Creidi, Antoinette Turk, Elias Gergi, Car...",Sweden,"October 19, 2020",2005,99,When Lebanon's Civil War deprives Zozo of his ...,Dramas,11
7783,s7784,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,111,A scrappy but poor boy worms his way into a ty...,Dramas,11
7784,s7785,Movie,Zulu Man in Japan,NaN,Nasty C,NaN,"September 25, 2020",2019,44,"In this documentary, South African rapper Nast...",Documentaries,11
7785,s7786,TV Show,Zumbo's Just Desserts,NaN,"Adriano Zumbo, Rachel Khoo",Australia,"October 31, 2020",2019,1,Dessert wizard Adriano Zumbo looks for the nex...,International TV,11
7786,s7787,Movie,ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS,Sam Dunn,None,United Kingdom,"March 1, 2020",2019,90,This documentary delves into the mystique behi...,Documentaries,11

In [12]:
data["num_of_cast"]

0       11
1       11
2       11
3       11
4       11
        ..
7782    11
7783    11
7784    11
7785    11
7786    11
Name: num_of_cast, Length: 7787, dtype: int64

In [31]:
data["genre"].value_counts()

Dramas                  1384
Comedies                1074
Documentaries            751
Action                   721
International TV         690
Children                 502
Crime TV                 369
Kids                     359
Stand-Up                 354
Horror Movies            244
British TV               232
Docuseries               194
Anime Series             148
International Movies     114
TV Comedies              110
Reality TV               102
Classic Movies            77
TV Dramas                 62
Uncategorized             56
Thrillers                 49
TV Action                 37
Romantic TV               28
Classic                   21
Independent Movies        20
Anime Features            19
Music                     17
TV Shows                  12
Cult Movies               12
Sci-Fi                    11
TV Horror                 10
Romantic Movies            3
Spanish-Language           2
Sports Movies              1
TV Sci                     1
LGBTQ Movies               1
Name: genre, dtype: int64

In [36]:
data.groupby("genre").groups

{'Action': [3, 21, 44, 50, 68, 71, 88, 89, 90, 92, 96, 104, 117, 126, 127, 153, 157, 172, 251, 262, 267, 280, 298, 299, 301, 302, 309, 314, 332, 355, 368, 385, 391, 397, 406, 419, 438, 446, 454, 465, 507, 514, 518, 525, 529, 532, 546, 553, 564, 566, 581, 599, 601, 606, 625, 627, 631, 634, 635, 654, 655, 656, 657, 658, 659, 660, 661, 662, 682, 687, 688, 716, 717, 718, 752, 756, 764, 767, 774, 792, 843, 844, 845, 875, 890, 904, 933, 939, 944, 945, 951, 959, 960, 961, 962, 970, 974, 975, 979, 982, ...], 'Anime Features': [228, 253, 1334, 2179, 2204, 2976, 3264, 3798, 3971, 4135, 4159, 4599, 4896, 4897, 4900, 5863, 6384, 7424, 7713], 'Anime Series': [24, 141, 260, 341, 360, 363, 516, 540, 556, 616, 651, 676, 703, 704, 705, 784, 868, 869, 870, 871, 872, 947, 973, 988, 995, 1006, 1165, 1202, 1212, 1225, 1233, 1240, 1253, 1335, 1406, 1447, 1560, 1561, 1728, 1767, 1769, 1830, 1845, 1848, 1875, 1897, 2020, 2090, 2125, 2126, 2128, 2129, 2217, 2238, 2313, 2359, 2395, 2431, 2438, 2439, 2451, 2511, 2525, 2555, 2557, 2576, 2708, 2715, 2869, 2936, 2999, 3036, 3061, 3125, 3213, 3261, 3263, 3279, 3338, 3379, 3422, 3472, 3473, 3541, 3612, 3677, 3734, 3783, 3852, 3853, 3870, 3932, 3959, 3960, 4019, 4157, 4158, 4204, 4385, 4404, ...], 'British TV': [58, 85, 142, 258, 321, 324, 335, 350, 398, 449, 669, 686, 690, 702, 768, 811, 902, 949, 956, 1000, 1048, 1061, 1062, 1108, 1125, 1148, 1162, 1181, 1249, 1314, 1315, 1386, 1399, 1404, 1417, 1441, 1462, 1487, 1519, 1522, 1526, 1532, 1541, 1549, 1577, 1596, 1597, 1599, 1652, 1703, 1706, 1710, 1784, 1792, 1844, 1906, 1907, 1923, 2000, 2048, 2073, 2092, 2130, 2176, 2211, 2235, 2271, 2299, 2373, 2374, 2381, 2419, 2441, 2513, 2523, 2528, 2616, 2633, 2744, 2751, 2754, 2758, 2764, 2808, 2810, 2846, 2872, 2886, 2887, 2987, 3014, 3017, 3018, 3025, 3102, 3118, 3219, 3389, 3403, 3412, ...], 'Children': [113, 145, 147, 155, 159, 160, 161, 163, 164, 167, 177, 178, 179, 186, 217, 227, 233, 242, 244, 254, 255, 285, 300, 374, 399, 400, 408, 413, 432, 433, 485, 486, 487, 488, 519, 520, 528, 538, 548, 571, 588, 675, 708, 709, 710, 733, 734, 737, 738, 739, 741, 742, 743, 744, 745, 746, 747, 782, 787, 802, 803, 834, 835, 836, 857, 889, 894, 895, 896, 897, 903, 905, 909, 911, 981, 1013, 1015, 1030, 1066, 1077, 1119, 1120, 1121, 1175, 1176, 1177, 1188, 1197, 1203, 1206, 1207, 1223, 1247, 1255, 1279, 1283, 1285, 1317, 1319, 1322, ...], 'Classic': [632, 1300, 1949, 2015, 2263, 2288, 2292, 2658, 3152, 3505, 4811, 5286, 5785, 5787, 5795, 5912, 6082, 6953, 6983, 7169, 7280], 'Classic Movies': [165, 381, 382, 392, 490, 758, 770, 822, 1016, 1152, 1169, 1226, 1241, 1385, 1497, 1620, 1628, 1793, 2150, 2152, 2251, 2410, 2463, 2493, 2522, 2827, 2853, 2859, 3361, 3425, 3487, 3525, 3608, 3639, 3707, 4008, 4218, 4436, 4701, 4776, 4844, 4960, 5002, 5063, 5070, 5089, 5122, 5285, 5371, 5376, 5425, 5430, 5846, 5848, 5981, 5994, 6117, 6141, 6221, 6256, 6337, 6544, 6556, 6613, 6657, 6698, 6699, 6731, 6868, 7072, 7242, 7268, 7342, 7538, 7570, 7609, 7635], 'Comedies': [18, 33, 34, 36, 37, 39, 40, 42, 48, 49, 72, 77, 78, 84, 94, 100, 102, 103, 114, 115, 118, 119, 120, 121, 122, 124, 131, 135, 143, 148, 154, 156, 174, 176, 183, 187, 203, 204, 210, 219, 226, 238, 240, 243, 247, 264, 265, 266, 274, 277, 283, 286, 287, 292, 311, 317, 352, 356, 358, 362, 369, 371, 377, 379, 388, 394, 403, 416, 420, 421, 423, 427, 439, 445, 472, 473, 479, 489, 491, 497, 498, 499, 502, 506, 508, 522, 547, 552, 573, 580, 587, 592, 604, 614, 618, 626, 643, 665, 670, 671, ...], 'Crime TV': [11, 12, 45, 63, 64, 80, 87, 202, 213, 290, 303, 333, 337, 340, 367, 389, 437, 457, 458, 475, 545, 558, 559, 565, 584, 615, 672, 685, 693, 694, 761, 766, 791, 815, 858, 859, 941, 952, 958, 965, 989, 1047, 1049, 1050, 1079, 1089, 1115, 1150, 1186, 1201, 1208, 1221, 1231, 1350, 1422, 1442, 1454, 1455, 1491, 1511, 1534, 1535, 1536, 1537, 1538, 1539, 1540, 1584, 1594, 1608, 1610, 1613, 1641, 1658, 1680, 1681, 1691, 1699, 1711, 1731, 1744, 1772, 1773, 1797, 1815, 1828, 1881, 1882, 1883, 1890, 1920, 1946, 1947, 1948, 1954, 1955, 1959, 1963, 1978, 2003, ...], 'Cult Movies': [1200, 1331, 1777, 2163, 3840, 4660, 5971, 6198, 6499, 6793, 6923, 7774], 'Documentaries': [13, 25, 28, 30, 35, 52, 56, 66, 70, 79, 93, 101, 110, 146, 169, 181, 182, 189, 193, 194, 200, 207, 208, 216, 223, 237, 252, 281, 325, 326, 327, 328, 347, 376, 383, 390, 395, 401, 414, 435, 436, 442, 443, 450, 453, 456, 459, 461, 462, 463, 469, 470, 481, 484, 511, 512, 554, 557, 561, 579, 600, 607, 611, 617, 620, 623, 636, 645, 673, 696, 728, 732, 763, 775, 780, 790, 799, 808, 810, 812, 813, 817, 818, 821, 824, 832, 853, 854, 860, 861, 874, 877, 908, 910, 912, 913, 920, 925, 928, 935, ...], 'Docuseries': [53, 134, 137, 138, 139, 140, 256, 288, 289, 319, 322, 338, 451, 460, 504, 531, 549, 569, 597, 624, 667, 759, 783, 800, 1018, 1021, 1073, 1085, 1088, 1109, 1184, 1189, 1264, 1291, 1298, 1304, 1305, 1306, 1308, 1326, 1359, 1412, 1439, 1479, 1483, 1494, 1503, 1533, 1619, 1627, 1659, 1743, 1768, 1796, 1839, 1933, 1995, 2027, 2068, 2158, 2171, 2180, 2186, 2196, 2203, 2207, 2214, 2218, 2246, 2285, 2360, 2430, 2526, 2595, 2672, 2730, 2731, 2735, 2745, 2753, 2786, 2821, 2882, 2941, 2952, 3011, 3016, 3069, 3223, 3333, 3334, 3335, 3336, 3340, 3436, 3441, 3531, 3538, 3556, 3575, ...], 'Dramas': [1, 4, 7, 10, 15, 17, 20, 22, 23, 31, 32, 43, 46, 47, 54, 57, 59, 60, 73, 74, 83, 91, 97, 98, 99, 105, 106, 107, 116, 123, 125, 128, 133, 136, 144, 149, 150, 151, 158, 166, 168, 170, 173, 175, 185, 192, 196, 201, 205, 206, 209, 211, 212, 214, 215, 222, 224, 229, 230, 231, 232, 234, 236, 245, 250, 257, 263, 268, 270, 271, 272, 273, 278, 279, 282, 291, 295, 296, 297, 304, 308, 313, 316, 323, 329, 330, 331, 334, 343, 346, 351, 353, 361, 372, 373, 384, 402, 407, 418, 422, ...], 'Horror Movies': [2, 6, 8, 9, 27, 41, 62, 65, 69, 75, 76, 129, 184, 261, 275, 315, 345, 415, 417, 509, 510, 530, 562, 563, 591, 602, 637, 681, 807, 892, 1132, 1161, 1164, 1183, 1228, 1232, 1312, 1418, 1482, 1530, 1531, 1551, 1572, 1573, 1574, 1605, 1614, 1615, 1618, 1621, 1642, 1654, 1671, 1672, 1673, 1694, 1700, 1715, 1727, 1811, 1818, 1821, 1929, 1976, 1987, 2023, 2043, 2104, 2164, 2165, 2188, 2286, 2287, 2342, 2343, 2344, 2365, 2379, 2394, 2400, 2405, 2422, 2505, 2532, 2611, 2654, 2659, 2668, 2669, 2704, 2721, 2747, 2748, 2811, 2831, 2833, 2865, 2877, 2884, 2902, ...], 'Independent Movies': [14, 689, 833, 1001, 1097, 1136, 1151, 1345, 1655, 1657, 1921, 2004, 2266, 2473, 2961, 3551, 4052, 6191, 6332, 6717], 'International Movies': [81, 109, 221, 249, 269, 293, 318, 354, 366, 410, 441, 500, 582, 629, 700, 711, 840, 1068, 1134, 1158, 1371, 1676, 1683, 1707, 1752, 1761, 1806, 1915, 1938, 1972, 2031, 2101, 2151, 2167, 2236, 2339, 2368, 2383, 2389, 2464, 2517, 2603, 2722, 2740, 2862, 2896, 2931, 2968, 3063, 3203, 3251, 3285, 3311, 3434, 3442, 3453, 3471, 3482, 3494, 3528, 3758, 3769, 3806, 3829, 3850, 3871, 4000, 4107, 4262, 4302, 4341, 4441, 4577, 4847, 4885, 4962, 5009, 5090, 5347, 5616, 5813, 5875, 5931, 5986, 6041, 6058, 6150, 6195, 6287, 6380, 6394, 6484, 6503, 6504, 6579, 6763, 6835, 6872, 6985, 6987, ...], 'International TV': [0, 5, 16, 38, 51, 61, 86, 95, 112, 152, 180, 188, 191, 198, 199, 218, 235, 239, 241, 248, 284, 294, 336, 339, 348, 349, 359, 365, 393, 409, 426, 440, 478, 494, 515, 533, 534, 539, 544, 575, 576, 586, 596, 609, 610, 630, 641, 668, 677, 680, 698, 707, 720, 721, 723, 724, 725, 726, 731, 750, 777, 778, 788, 793, 797, 805, 814, 850, 856, 862, 879, 880, 881, 898, 929, 931, 940, 948, 972, 984, 985, 992, 994, 1028, 1042, 1051, 1052, 1064, 1070, 1092, 1105, 1107, 1110, 1124, 1144, 1163, 1168, 1178, 1179, 1180, ...], 'Kids': [108, 111, 225, 276, 364, 380, 396, 411, 412, 434, 523, 570, 598, 706, 735, 736, 740, 760, 779, 786, 825, 828, 829, 855, 899, 1010, 1043, 1044, 1075, 1083, 1127, 1139, 1140, 1173, 1174, 1213, 1214, 1222, 1282, 1316, 1321, 1328, 1341, 1376, 1377, 1382, 1413, 1444, 1445, 1448, 1529, 1553, 1586, 1639, 1646, 1770, 1771, 1856, 1857, 1866, 1867, 1869, 1870, 1871, 1872, 1873, 1905, 1991, 2017, 2044, 2106, 2112, 2120, 2210, 2306, 2327, 2340, 2380, 2409, 2437, 2446, 2448, 2467, 2498, 2501, 2530, 2534, 2543, 2559, 2567, 2568, 2635, 2640, 2647, 2652, 2684, 2685, 2693, 2699, 2741, ...], 'LGBTQ Movies': [7557], 'Music': [246, 748, 830, 1008, 2268, 2358, 3257, 3480, 3735, 4054, 5025, 5142, 5550, 5771, 5996, 7091, 7092], 'Reality TV': [26, 130, 428, 452, 574, 639, 769, 849, 953, 980, 1039, 1046, 1082, 1209, 1289, 1299, 1495, 1496, 1508, 1591, 1625, 1669, 1695, 1826, 1864, 1880, 1994, 2121, 2199, 2206, 2209, 2230, 2241, 2385, 2402, 2651, 2738, 2763, 2771, 2883, 2928, 2938, 2989, 3004, 3021, 3113, 3149, 3619, 3854, 3950, 4020, 4103, 4118, 4386, 4389, 4459, 4704, 4802, 4959, 5037, 5193, 5413, 5419, 5426, 5489, 5584, 5621, 5630, 5646, 5648, 5649, 5669, 5731, 5803, 5850, 5864, 5873, 5874, 5911, 5926, 6009, 6076, 6077, 6104, 6105, 6161, 6193, 6207, 6210, 6222, 6351, 6407, 6529, 6802, 7074, 7106, 7148, 7154, 7303, 7304, ...], 'Romantic Movies': [2792, 4140, 4856], 'Romantic TV': [640, 819, 1100, 1523, 1624, 1640, 1861, 1951, 1990, 2139, 2289, 2411, 2538, 2818, 3122, 3739, 4451, 4496, 4614, 4706, 5556, 5609, 5729, 5791, 5938, 6382, 6540, 7431], 'Sci-Fi': [82, 3426, 3516, 4298, 4991, 5488, 5992, 6163, 6869, 7186, 7594], 'Spanish-Language': [3147, 3490], 'Sports Movies': [19], 'Stand-Up': [197, 220, 305, 307, 310, 312, 320, 344, 370, 375, 378, 386, 387, 477, 482, 483, 535, 550, 551, 568, 577, 578, 585, 648, 649, 650, 846, 847, 848, 852, 876, 914, 915, 916, 917, 918, 919, 921, 922, 923, 924, 1009, 1071, 1096, 1101, 1138, 1219, 1220, 1251, 1307, 1309, 1310, 1340, 1352, 1353, 1354, 1355, 1356, 1357, 1360, 1443, 1458, 1459, 1460, 1470, 1471, 1472, 1516, 1543, 1563, 1564, 1585, 1600, 1601, 1602, 1606, 1629, 1630, 1631, 1632, 1634, 1636, 1684, 1696, 1697, 1702, 1704, 1705, 1753, 1765, 1822, 1840, 1918, 1919, 1925, 1926, 1956, 1981, 2007, 2021, ...], 'TV Action': [543, 595, 954, 966, 1440, 1465, 1555, 1643, 1647, 1780, 2337, 3030, 3697, 3733, 3784, 3935, 3962, 4567, 4705, 5137, 5741, 5786, 5788, 5789, 5908, 6047, 6267, 6476, 6592, 6862, 6958, 7006, 7380, 7386, 7484, 7677, 7755], 'TV Comedies': [29, 306, 357, 404, 583, 603, 619, 621, 906, 1025, 1040, 1095, 1118, 1193, 1270, 1475, 1653, 1666, 1781, 1794, 1910, 1911, 2050, 2083, 2201, 2311, 2375, 2412, 2425, 2427, 2428, 2435, 2440, 2508, 2524, 2582, 2618, 2625, 2638, 2648, 2800, 2856, 2899, 2917, 2926, 3010, 3077, 3087, 3316, 3395, 3515, 3685, 3899, 3907, 3944, 3946, 3985, 4048, 4075, 4160, 4252, 4370, 4371, 4444, 4448, 4449, 4552, 4581, 4639, 4652, 4677, 4763, 4779, 4912, 4980, 5117, 5291, 5315, 5380, 5431, 5494, 5538, 5640, 5680, 5688, 5733, 5742, 6043, 6259, 6358, 6405, 6430, 6478, 6539, 6565, 6664, 6718, 6741, 6770, 6801, ...], 'TV Dramas': [259, 405, 471, 991, 1284, 1415, 1488, 1802, 1900, 2051, 2457, 2491, 2503, 2512, 2535, 2562, 2587, 2678, 2739, 2777, 2832, 3401, 3421, 3568, 3631, 3730, 3838, 3844, 4053, 4513, 4821, 4914, 5102, 5146, 5486, 5487, 5536, 5755, 5972, 5973, 6056, 6157, 6372, 6388, 6439, 6440, 6634, 6660, 6678, 6710, 6715, 6727, 6796, 6885, 6950, 6974, 6996, 7107, 7224, 7274, 7544, 7578], 'TV Horror': [468, 1268, 1338, 2600, 2687, 2697, 4470, 5660, 5836, 7289], 'TV Sci': [1616], 'TV Shows': [132, 195, 1012, 1103, 1336, 2458, 4055, 4866, 4867, 5644, 6038, 6435], 'Thrillers': [190, 431, 464, 521, 638, 695, 865, 969, 1499, 1598, 1722, 1725, 1782, 1833, 2097, 2109, 2123, 2253, 2468, 2596, 2679, 2983, 3106, 3292, 3385, 3413, 3686, 4174, 4362, 4661, 4753, 4828, 4966, 5305, 5316, 5461, 5668, 5674, 5781, 6262, 6314, 6833, 6909, 6944, 6946, 6975, 7023, 7287, 7504], 'Uncategorized': [55, 67, 162, 171, 342, 1026, 1128, 1318, 1320, 1429, 1570, 1708, 1709, 2177, 2178, 2300, 2301, 3115, 3253, 3560, 3561, 3579, 3736, 3737, 3738, 3936, 3943, 4187, 4418, 4467, 4539, 4572, 4573, 4729, 4812, 4888, 4889, 4890, 4891, 4892, 4893, 4942, 4944, 4946, 4949, 5383, 5575, 5576, 5577, 6465, 6735, 7170, 7171, 7179, 7250, 7671]}

In [37]:
data.groupby("type")["genre"].value_counts()

type     genre
Movie    Dramas                  1384
         Comedies                1074
         Documentaries            751
         Action                   721
         Children                 502
         Stand-Up                 321
         Horror Movies            244
         International Movies     114
         Classic Movies            77
         Uncategorized             56
         Thrillers                 49
         Independent Movies        20
         Anime Features            19
         Music                     17
         Cult Movies               12
         Sci-Fi                    11
         Romantic Movies            3
         LGBTQ Movies               1
         Sports Movies              1
TV Show  International TV         690
         Crime TV                 369
         Kids                     359
         British TV               232
         Docuseries               194
         Anime Series             148
         TV Comedies              110
         Reality TV               102
         TV Dramas                 62
         TV Action                 37
         Stand-Up                  33
         Romantic TV               28
         Classic                   21
         TV Shows                  12
         TV Horror                 10
         Spanish-Language           2
         TV Sci                     1
Name: genre, dtype: int64